apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seafile-ingress
  namespace: seafile
  labels:
    app: seafile
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: {{ .Values.seafile.ingress.ingressClassName }}
  tls:
    - hosts:
        - {{ .Values.seafile.env.SEAFILE_SERVER_HOSTNAME }}
      secretName: seafile-tls
  rules:
    - host: {{ .Values.seafile.env.SEAFILE_SERVER_HOSTNAME }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: seafile
                port:
                  number: 80