apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seafile-ingress
  labels:
    app: seafile
  {{- if .Values.seafile.ingress.annotations }}
  annotations:
    {{- toYaml .Values.seafile.ingress.annotations | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.seafile.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.seafile.env.SEAFILE_SERVER_HOSTNAME }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: seafile
                port:
                  number: 80