{{- if include "seafile.seafileDataVolume.enabled" . | eq "true" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seafile-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ include "seafile.seafileDataVolume.storage" . }}
  {{- if and .Values.seafile.configs.seafileDataVolume .Values.seafile.configs.seafileDataVolume.storageClassName }}
  storageClassName: {{ .Values.seafile.configs.seafileDataVolume.storageClassName }}
  {{- end }}
{{- end }}