apiVersion: apps/v1
kind: Deployment
metadata:
  name: seafile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seafile
  template:
    metadata:
      labels:
        app: seafile
    spec:
      enableServiceLinks: false
      {{- if eq (include "seafile.seafileDataVolume.enabled" . | trim) "true" }}
      initContainers:
        - name: set-ownership
          image: busybox
          command: ['sh', '-c', 'chown -R root:root /shared']
          volumeMounts:
            - name: seafile-data
              mountPath: /shared
      {{- end }}

      containers:
        - name: seafile
          image: {{ include "seafile.image" . }}
          env:
            - name: SEAF_SERVER_STORAGE_TYPE
              value: "disk"
            - name: SEAFILE_AI_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: seafile-secret
                  key: JWT_PRIVATE_KEY
            {{- if .Values.seafile.extraEnv }}
            {{- toYaml .Values.seafile.extraEnv | nindent 12 }}
            {{- end }}

          envFrom:
            - configMapRef:
                name: seafile-env
            - secretRef:
                name: seafile-secret

          ports:
            - containerPort: 80

          {{- if eq (include "seafile.seafileDataVolume.enabled" . | trim) "true" }}
          volumeMounts:
            - name: seafile-data
              mountPath: /shared

            # Only override individual files, not the whole /scripts folder
            - name: seafile-patch-volume
              mountPath: /scripts/bootstrap.py
              subPath: bootstrap.py
            - name: seafile-patch-volume
              mountPath: /opt/seafile/seafile-server-11.0.13/setup-seafile-mysql.py
              subPath: setup-seafile-mysql.py

            {{- range .Values.seafile.extraVolumes }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              {{- if .subPath }}
              subPath: {{ .subPath }}
              {{- end }}
              {{- if .readOnly }}
              readOnly: {{ .readOnly }}
              {{- end }}
            {{- end }}
          {{- end }}

          resources:
            {{- toYaml .Values.seafile.resources | nindent 12 }}

      {{- if eq (include "seafile.seafileDataVolume.enabled" . | trim) "true" }}
      volumes:
        - name: seafile-data
          persistentVolumeClaim:
            claimName: seafile-data

        - name: seafile-patch-volume
          configMap:
            name: seafile-patch-scripts
            items:
              - key: bootstrap.py
                path: bootstrap.py
              - key: setup-seafile-mysql.py
                path: setup-seafile-mysql.py

        {{- range .Values.seafile.extraVolumes }}
        - name: {{ .name }}
          {{- toYaml .volumeInfo | nindent 10 }}
        {{- end }}

      {{- end }}

      restartPolicy: Always
