{{- if .Values.seafile.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seafile-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.seafile.persistence.size }}
  {{- if .Values.seafile.persistence.storageClassName }}
  storageClassName: {{ .Values.seafile.persistence.storageClassName }}
  {{- end }}
{{- end }}