apiVersion: v2
name: ce
description: Helm chart for Seafile CE.
type: application
version: "13.0.2"
appVersion: "13.0"
home: https://seafile.com
sources:
  - https://github.com/haiwen/seafile
maintainers:
  - name: seafileDocs
icon: https://de.seafile.com/wp-content/themes/seafileger/img/svg/seafile_logo_proposed.svg